version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: machine_visibility_postgres
    environment:
      POSTGRES_DB: visibility_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: